name: Build demo.zip

on:
  workflow_dispatch:
  push:
    tags:
      - 0.*
      - 1.*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Install Java ♨️
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Build 🔧
        env:
          DEFOLD_BOB_SHA1: ${{ secrets.DEFOLD_BOB_SHA1 }}
        run: |
          lsb_release -a

          mkdir -p build/bundle/public

          # This demo doesn't implement Service Worker and Native Cache, so remove them from the settings:
          sed -i 's/service_worker_url = .*//' game.project
          sed -i 's/manifest_url = .*//' game.project

          BOB_SHA1=${DEFOLD_BOB_SHA1:-$(curl -s 'https://d.defold.com/stable/info.json' | jq -r .sha1)}
          BOB_LOCAL_SHA1=$((java -jar build/bundle/bob.jar --version | cut -d' ' -f6) || true)
          if [ "${BOB_LOCAL_SHA1}" != "${BOB_SHA1}" ]; then wget --progress=dot:mega -O build/bundle/bob.jar "https://d.defold.com/archive/${BOB_SHA1}/bob/bob.jar"; fi
          java -jar build/bundle/bob.jar --version

          java -jar build/bundle/bob.jar --email foo@bar.com --auth 12345 --texture-compression true --bundle-output build/bundle/js-web --platform js-web --archive --variant release resolve build bundle
          (cd build/bundle/js-web/* && zip -r ../../public/demo.zip .)

      - name: Deploy to Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/bundle/public
